### ISSUE TITLE
Appears to not be working now

### ISSUE THREAD

**Issue by lmiller1990** [chanlito/vue-cli-plugin-tsx-support#2]
This plugin seems to not be working for me anymore.

Repro:

1. create new project with vue cli (with babel and TS as per readme)
2. `vue add tsx-support`

Gives this

```
You may need an appropriate loader to handle this file type.
```

**Comment by chanlito** [comment]
@lmiller1990 Do you have a repo I can test? Because I just tried and it's working fine.
